# Generated by Django 3.1.1 on 2020-10-06 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BepUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('account', models.CharField(editable=False, max_length=30)),
                ('password_hash', models.CharField(editable=False, max_length=100)),
                ('password_salt', models.CharField(editable=False, max_length=100)),
                ('name', models.CharField(max_length=50)),
                ('account_balances', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('phone_number', models.CharField(max_length=20)),
                ('deals', models.IntegerField(default=0)),
                ('address', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('publish_id', models.IntegerField(editable=False)),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('is_need', models.BooleanField(default=False)),
                ('isbn', models.CharField(default='', max_length=20)),
                ('author', models.CharField(default='', max_length=50)),
                ('pub_time', models.DateTimeField(auto_now=True)),
                ('cover', models.ImageField(upload_to='uploads/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('book_id', models.IntegerField(editable=False)),
                ('owner_id', models.IntegerField(editable=False, unique=True)),
                ('purchaser_id', models.IntegerField(editable=False)),
                ('reserved_place', models.CharField(max_length=100)),
                ('pub_time', models.DateTimeField(auto_now=True)),
                ('payed', models.BooleanField(default=False)),
                ('deprecated', models.BooleanField(default=False)),
                ('finished', models.BooleanField(default=False)),
                ('rate', models.IntegerField(default=5)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bep_user_id', models.IntegerField(editable=False)),
                ('session_str', models.CharField(max_length=200)),
            ],
        ),
    ]
